/* Copyright (c) 2021-2026 Richard Rodger, MIT License */

// Generated by ../embed-translate.js. Edit tabnas.plugin.json or alchemy/*,
// then run npm run embed.

type TranslationPart = Readonly<{
  entry: string
  source?: string
}>

type TranslationParts = Readonly<{
  manifest: string
  lift?: TranslationPart
  embed?: TranslationPart
  render?: TranslationPart
}>

const TRANSLATION: TranslationParts = Object.freeze({
  manifest: `{
  "$schema": "https://tabnas.dev/schema/plugin.schema.json",
  "name": "@tabnas/semver",
  "go": "github.com/tabnas/semver/go",
  "rust": "tabnas-semver",
  "description": "Semantic Versioning 2.0.0 (semver.org) parsing for the tabnas engine, compiled from an ABNF grammar.",
  "engine": "@tabnas/parser",
  "grammar": "semver-grammar.abnf",
  "languageId": "semver",
  "pluginKind": "grammar",
  "grammarKind": "closure",
  "lexStream": "clean",
  "syncGroups": [
    "end"
  ],
  "specDir": "test/spec",
  "clib": {
    "dir": "go/clib",
    "library": "libtabnassemver",
    "abi": "v1",
    "errorCodes": [
      "usage",
      "grammar",
      "handle",
      "internal"
    ]
  },
  "errorCodes": [],
  "docs": "https://tabnas.dev/docs/packages",
  "repository": "https://github.com/tabnas/semver",
  "versionSource": "ts/package.json",
  "translate": {
    "reads": "tree",
    "writes": "tree",
    "root": "object",
    "schema": "semver",
    "embed": "alchemy/embed.alc",
    "render": "alchemy/render.alc",
    "loss": [
      "Members other than major, minor, patch, prerelease and build are not written.",
      "A prerelease or build that is absent, null, empty or an empty list is not written, and reads back as an empty list.",
      "A prerelease or build given as one string is written as it is, after its hyphen or plus sign, and reads back as the list of its dot-separated identifiers.",
      "A major, minor, patch or prerelease identifier given as a string of digits reads back as a number, as the reader builds one, and a build identifier given as a number reads back as a string of its digits."
    ]
  }
}
`,
  embed: Object.freeze({ entry: "semver-embed", source: `; Semantic Versioning's embedding: a plain tree that is a version, as the
; version tree the reader builds and the render writes, and back again.
; This is a library of definitions, each named \`semver-...\`, which a host
; links with its own program and with the render (alchemy's
; \`compile_sources\`). It has two entry points: \`semver-embed\` takes a
; plain tree's events to a version's, and \`semver-unembed\`, its reverse,
; takes a version's events back. Nothing else here is the host's to call.
;
; A version has nowhere to put any other tree, so the embedding is the
; identity on the trees that are one and refuses the rest. A tree is a
; version when its root is an object whose \`major\`, \`minor\` and \`patch\`
; are whole numbers written in digits (a number whose text is digits
; alone, or a string of digits, which is how the Rust reader keeps one
; past 2^53 - 1), and whose \`prerelease\` and \`build\`, where it has them,
; are each a list of identifiers or one string of identifiers joined by
; dots, or null or empty. An identifier is a string of \`0-9\`, \`A-Z\`,
; \`a-z\` and \`-\`, not empty, or a number written in digits, and a
; prerelease identifier of digits does not begin with a zero; a string
; of identifiers is split at its dots and each identifier checked so, as
; one in a list is. Every other member passes through, and the render
; does not write it. Each check is the render's, and so is each failure:
; any other tree fails with TARGET_VALUE_UNREPRESENTABLE, saying what a
; version needs, before the render writes anything, and events no tree
; has fail with PROTOCOL_ORDER_ERROR. A string of digits that begins with
; a zero is told by its characters, as the render tells it (see
; \`alchemy/render.alc\`).
;
; The reverse is the identity: the reader builds a version's tree, and a
; version's tree is a plain tree. What it reads back is what the render
; wrote, so what the render does not keep (the manifest's loss list) is
; what the round trip changes: a member of the version's own is gone, an
; absent prerelease or build reads back as an empty list, one string of
; identifiers as the list of them, and an identifier as the reader builds
; it.
;
; The state is the render's, a stack of markers, one for each container
; the embedding is inside (see \`alchemy/render.alc\`): \`[:version phase
; major minor patch prerelease build]\`, \`[:ids name texts]\` and \`[:skip
; open]\`, and \`[:done]\` once the version has ended.

def semver-embed-needs
  "a version is an object whose major, minor and patch are whole numbers written in digits, with an optional prerelease and build, each a list of identifiers or one string of them"

def semver-embed-digits [[48 57]]
def semver-embed-identifier-chars [[45 45] [48 57] [65 90] [97 122]]

def semver-embed-fail [what]
  fail :unrepresentable (string-join "" ["the document is not a version: " what "; " semver-embed-needs])

def semver-embed-kind [value]
  match (kind value)
    case :null "null"
    case :boolean "a boolean"
    case :number "a number"
    case :string "a string"
    case _ "a container"

def semver-embed-leading-zero [s]
  if (is-number s) false true

def semver-embed-number [what value]
  match (number-class value)
    case :finite
      let [text (scalar-text csv-options value)]
        if (chars-within semver-embed-digits text)
          text
          semver-embed-fail (string-join "" [what " is " text ", which is not a whole number written in digits"])
    case _ (semver-embed-fail (string-join "" [what " is a number that is not finite"]))

def semver-embed-digit-string [what value]
  match (compare (length value) 0)
    case :greater
      if (chars-within semver-embed-digits value)
        if (semver-embed-leading-zero value)
          semver-embed-fail (string-join "" [what " is " (quoted value) ", which begins with a zero"])
          value
        semver-embed-fail (string-join "" [what " is " (quoted value) ", which is not digits"])
    case _ (semver-embed-fail (string-join "" [what " is the empty string"]))

def semver-embed-core [name value]
  match (kind value)
    case :number (semver-embed-number name value)
    case :string (semver-embed-digit-string name value)
    case _ (semver-embed-fail (string-join "" [name " is " (semver-embed-kind value)]))

def semver-embed-identifier [name what value]
  match (kind value)
    case :number (semver-embed-number what value)
    case :string
      match (compare (length value) 0)
        case :greater
          if (chars-within semver-embed-identifier-chars value)
            if (chars-within semver-embed-digits value)
              match name
                case "prerelease" (semver-embed-digit-string what value)
                case _ value
              value
            semver-embed-fail (string-join "" [what " is " (quoted value) ", where an identifier holds 0-9, A-Z, a-z and -"])
        case _ (semver-embed-fail (string-join "" [what " is the empty string"]))
    case _ (semver-embed-fail (string-join "" [what " is " (semver-embed-kind value)]))

def semver-embed-optional [name value]
  match (kind value)
    case :null :none
    case :string
      match value
        case "" :none
        case _ (map (partial semver-embed-identifier name (string-join "" ["an identifier of the " name " " (quoted value)])) (split "." value))
    case _ (semver-embed-fail (string-join "" ["the " name " is " (semver-embed-kind value) ", where it is a list of identifiers or one string of them"]))

def semver-embed-top [s]
  match (count s)
    case 0 :none
    case _ (top s)

def semver-embed-mark [marker s]
  push marker (pop s)

def semver-embed-set [m name text]
  match m
    case [:version _ ma mi pa pr bu]
      match name
        case "major" [:version :key text mi pa pr bu]
        case "minor" [:version :key ma text pa pr bu]
        case "patch" [:version :key ma mi text pr bu]
        case "prerelease" [:version :key ma mi pa text bu]
        case "build" [:version :key ma mi pa pr text]

def semver-embed-phase [m phase]
  match m
    case [:version _ ma mi pa pr bu] [:version phase ma mi pa pr bu]

def semver-embed-key [s m name]
  match name
    case "major" (semver-embed-mark (semver-embed-phase m [:value name]) s)
    case "minor" (semver-embed-mark (semver-embed-phase m [:value name]) s)
    case "patch" (semver-embed-mark (semver-embed-phase m [:value name]) s)
    case "prerelease" (semver-embed-mark (semver-embed-phase m [:value name]) s)
    case "build" (semver-embed-mark (semver-embed-phase m [:value name]) s)
    case _ (push [:skip []] s)

def semver-embed-part [s m name value]
  match name
    case "prerelease" (semver-embed-mark (semver-embed-set m name (semver-embed-optional name value)) s)
    case "build" (semver-embed-mark (semver-embed-set m name (semver-embed-optional name value)) s)
    case _ (semver-embed-mark (semver-embed-set m name (semver-embed-core name value)) s)

def semver-embed-open [s name container]
  match [name container]
    case ["prerelease" :array] (push [:ids name []] s)
    case ["build" :array] (push [:ids name []] s)
    case [_ :array] (semver-embed-fail (string-join "" [name " is a list"]))
    case _ (semver-embed-fail (string-join "" [name " is an object"]))

def semver-embed-ids-end [s name texts]
  let [rest (pop s)]
    match (count texts)
      case 0 (semver-embed-mark (semver-embed-set (top rest) name :none) rest)
      case _ (semver-embed-mark (semver-embed-set (top rest) name texts) rest)

; The version has ended: it must have its three numbers.
def semver-embed-end [m]
  match m
    case [:version _ :none _ _ _ _] (semver-embed-fail "it has no major")
    case [:version _ _ :none _ _ _] (semver-embed-fail "it has no minor")
    case [:version _ _ _ :none _ _] (semver-embed-fail "it has no patch")
    case _ [[:done]]

def semver-embed-skip-value [s open]
  match (semver-embed-top open)
    case :none (pop s)
    case :member (semver-embed-mark [:skip (semver-embed-mark :object open)] s)
    case :array s
    case :object (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

def semver-embed-skip-open [s open container]
  match (semver-embed-top open)
    case :none (semver-embed-mark [:skip (push container open)] s)
    case :member (semver-embed-mark [:skip (push container (semver-embed-mark :object open))] s)
    case :array (semver-embed-mark [:skip (push container open)] s)
    case :object (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

def semver-embed-skip-close [s open container]
  match [(semver-embed-top open) container]
    case [:object :object] (semver-embed-skip-closed s (pop open))
    case [:array :array] (semver-embed-skip-closed s (pop open))
    case _ (fail :protocol-order "the events end a container that is not open, or one whose member has no value, which a tree's never do")

def semver-embed-skip-closed [s open]
  match (count open)
    case 0 (pop s)
    case _ (semver-embed-mark [:skip open] s)

def semver-embed-skip [s open event]
  match event
    case object-start (semver-embed-skip-open s open :object)
    case array-start (semver-embed-skip-open s open :array)
    case (key name)
      match (semver-embed-top open)
        case :object (semver-embed-mark [:skip (semver-embed-mark :member open)] s)
        case _ (fail :protocol-order "the events hold a key where a value is due, which a tree's never do")
    case (scalar value) (semver-embed-skip-value s open)
    case object-end (semver-embed-skip-close s open :object)
    case array-end (semver-embed-skip-close s open :array)

def semver-embed-root [event]
  match event
    case object-start [[:version :key :none :none :none :none :none]]
    case array-start (semver-embed-fail "its root is a list")
    case (scalar value) (semver-embed-fail (string-join "" ["its root is " (semver-embed-kind value)]))
    case _ (fail :protocol-order "the events begin with an end or a key, which a tree's never do")

; The state after an event.
def semver-embed-next [s event]
  match (semver-embed-top s)
    case :none (semver-embed-root event)
    case [:done] (fail :protocol-order "the events hold more after the root value, which a tree's never do")
    case [:skip open] (semver-embed-skip s open event)
    case [:ids name texts]
      match event
        case (scalar value) (semver-embed-mark [:ids name (push (semver-embed-identifier name (string-join "" ["an identifier of the " name]) value) texts)] s)
        case array-end (semver-embed-ids-end s name texts)
        case object-start (semver-embed-fail (string-join "" ["an identifier of the " name " is an object"]))
        case array-start (semver-embed-fail (string-join "" ["an identifier of the " name " is a list"]))
        case _ (fail :protocol-order "the events hold a key or an object's end inside a list, which a tree's never do")
    case [:version :key ma mi pa pr bu]
      match event
        case (key name) (semver-embed-key s [:version :key ma mi pa pr bu] name)
        case object-end (semver-embed-end [:version :key ma mi pa pr bu])
        case _ (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")
    case [:version [:value name] ma mi pa pr bu]
      match event
        case (scalar value) (semver-embed-part s [:version [:value name] ma mi pa pr bu] name value)
        case object-start (semver-embed-open s name :object)
        case array-start (semver-embed-open s name :array)
        case _ (fail :protocol-order "the events hold a key or an end where a value is due, which a tree's never do")

; Each event passes through once it is checked.
def semver-embed-step [s event]
  transition (semver-embed-next s event) [event]

def semver-embed-finish [s]
  match (semver-embed-top s)
    case [:done] []
    case :none (fail :protocol-order "the events hold no value, where a tree's hold one")
    case _ (fail :protocol-order "the events ended inside a container, which a tree's never do")

; The embedding: a plain tree's events in, a version's out, unchanged.
def semver-embed [input]
  as-events (scan-emit [] semver-embed-step semver-embed-finish (events input))

; The reverse: a version's events in, the plain tree's out, unchanged.
def semver-unembed [input]
  input
` }),
  render: Object.freeze({ entry: "semver-render", source: `; Semantic Versioning's render: a version's events written as its text,
; \`major.minor.patch[-prerelease][+build]\`. This is a library of
; definitions, each named \`semver-...\`, which a host links with its own
; program (alchemy's \`compile_sources\`); its entry point is
; \`semver-render\`, and nothing else here is the host's to call.
;
; The tree is the one the reader builds, an object whose members are
; \`major\`, \`minor\` and \`patch\`, \`prerelease\` (a list of identifiers, a
; number for one spelled in digits and a string for any other) and
; \`build\` (a list of identifiers, each a string), or one the embedding
; (\`alchemy/embed.alc\`) accepted, which may also give:
;
; - a \`major\`, \`minor\` or \`patch\` as a string of digits, which is how
;   the Rust reader keeps one past 2^53 - 1, where a number would round;
; - a \`prerelease\` or \`build\` as one string of identifiers and dots,
;   written as it is, or as null, the empty string or an empty list, none
;   of which is written;
; - a build identifier as a number spelled in digits;
; - members of its own, which are not written.
;
; A number is written as its text, its lexeme or as JSON writes it, and
; that text must be digits alone: a version's numbers are whole, and
; alchemy has no arithmetic to write \`1.0\` or \`1e3\` as \`1\`. A string of
; digits must not begin with a zero, unless it is \`0\`, since the
; specification forbids that in a version core and in a numeric
; identifier; it is told by its characters, with \`is-number\`, since JSON
; spells a number of digits alone as \`0\` or with no leading zero, however
; many digits it has. An identifier holds \`0-9\`, \`A-Z\`, \`a-z\` and \`-\` and
; is not empty. A string of identifiers is split at its dots, and each
; identifier is checked as one in a list is, so a string with an empty
; identifier (\`a..b\`, \`.a\`, \`a.\`) or a prerelease whose numeric
; identifier begins with a zero (\`01\`) fails as the list would.
;
; The text ends with no line break, since the reader takes one as a
; character no version has. It is written once, at the root's end, so a
; tree that is not a version writes nothing before it fails: a root that
; is not an object, a version without its major, minor or patch, or a
; value of the wrong kind fails with TARGET_VALUE_UNREPRESENTABLE, saying
; what a version needs, and events no tree has fail with
; PROTOCOL_ORDER_ERROR.
;
; The state is a stack of markers, one for each container the render is
; inside. The version's is \`[:version phase major minor patch prerelease
; build]\`, its phase \`:key\` while a member's key is due and \`[:value
; name]\` while its value is, each part \`:none\` or its text (a prerelease
; or a build the vector of its identifiers' texts). Above it, \`[:ids name
; texts]\` is a list of identifiers being read, and \`[:skip open]\` a
; member that is not written, \`open\` holding a marker for each of its
; containers that is open (\`:object\`, \`:member\` once its key is read,
; \`:array\`), so its events are held to a tree's order too. Once the
; version is written the state is \`[:done]\`, and nothing may follow it.

; What a version is, for the failures.
def semver-needs
  "a version is an object whose major, minor and patch are whole numbers written in digits, with an optional prerelease and build, each a list of identifiers or one string of them"

; The characters of a number and of an identifier, as code point ranges.
def semver-digits [[48 57]]
def semver-identifier-chars [[45 45] [48 57] [65 90] [97 122]]

def semver-fail [what]
  fail :unrepresentable (string-join "" ["the document is not a version: " what "; " semver-needs])

; A value's kind, in words.
def semver-kind [value]
  match (kind value)
    case :null "null"
    case :boolean "a boolean"
    case :number "a number"
    case :string "a string"
    case _ "a container"

; Whether a string of digits begins with a zero and is not \`0\`: JSON
; spells a number of digits alone as \`0\` or with no leading zero, and
; \`is-number\` reads a string's characters as JSON's spelling, so it
; answers false exactly then, however many digits there are.
def semver-leading-zero [s]
  if (is-number s) false true

; A number's text, which must be digits alone.
def semver-number [what value]
  match (number-class value)
    case :finite
      let [text (scalar-text csv-options value)]
        if (chars-within semver-digits text)
          text
          semver-fail (string-join "" [what " is " text ", which is not a whole number written in digits"])
    case _ (semver-fail (string-join "" [what " is a number that is not finite"]))

; A string of digits, with no leading zero.
def semver-digit-string [what value]
  match (compare (length value) 0)
    case :greater
      if (chars-within semver-digits value)
        if (semver-leading-zero value)
          semver-fail (string-join "" [what " is " (quoted value) ", which begins with a zero"])
          value
        semver-fail (string-join "" [what " is " (quoted value) ", which is not digits"])
    case _ (semver-fail (string-join "" [what " is the empty string"]))

; The text of a major, minor or patch.
def semver-core [name value]
  match (kind value)
    case :number (semver-number name value)
    case :string (semver-digit-string name value)
    case _ (semver-fail (string-join "" [name " is " (semver-kind value)]))

; The text of an identifier of a prerelease or a build, \`what\` naming it
; in a failure: a number in digits, or a string of an identifier's
; characters, which in a prerelease must not be digits with a leading
; zero.
def semver-identifier [name what value]
  match (kind value)
    case :number (semver-number what value)
    case :string
      match (compare (length value) 0)
        case :greater
          if (chars-within semver-identifier-chars value)
            if (chars-within semver-digits value)
              match name
                case "prerelease" (semver-digit-string what value)
                case _ value
              value
            semver-fail (string-join "" [what " is " (quoted value) ", where an identifier holds 0-9, A-Z, a-z and -"])
        case _ (semver-fail (string-join "" [what " is the empty string"]))
    case _ (semver-fail (string-join "" [what " is " (semver-kind value)]))

; A prerelease or a build given as a scalar: one string of identifiers
; joined by dots, each of them checked as one in a list is and written as
; it is, or null or the empty string, which is not written.
def semver-optional [name value]
  match (kind value)
    case :null :none
    case :string
      match value
        case "" :none
        case _ (map (partial semver-identifier name (string-join "" ["an identifier of the " name " " (quoted value)])) (split "." value))
    case _ (semver-fail (string-join "" ["the " name " is " (semver-kind value) ", where it is a list of identifiers or one string of them"]))

; The top marker, or :none before the root value.
def semver-top [s]
  match (count s)
    case 0 :none
    case _ (top s)

; The top marker replaced.
def semver-mark [marker s]
  push marker (pop s)

; The version's marker with one part set and its next key due.
def semver-set [m name text]
  match m
    case [:version _ ma mi pa pr bu]
      match name
        case "major" [:version :key text mi pa pr bu]
        case "minor" [:version :key ma text pa pr bu]
        case "patch" [:version :key ma mi text pr bu]
        case "prerelease" [:version :key ma mi pa text bu]
        case "build" [:version :key ma mi pa pr text]

; The version's marker in another phase.
def semver-phase [m phase]
  match m
    case [:version _ ma mi pa pr bu] [:version phase ma mi pa pr bu]

; A key of the version: its part's value is due, or a member that is not
; written begins.
def semver-key [s m name]
  match name
    case "major" (transition (semver-mark (semver-phase m [:value name]) s) [])
    case "minor" (transition (semver-mark (semver-phase m [:value name]) s) [])
    case "patch" (transition (semver-mark (semver-phase m [:value name]) s) [])
    case "prerelease" (transition (semver-mark (semver-phase m [:value name]) s) [])
    case "build" (transition (semver-mark (semver-phase m [:value name]) s) [])
    case _ (transition (push [:skip []] s) [])

; A scalar where a part's value is due.
def semver-part [s m name value]
  match name
    case "prerelease" (transition (semver-mark (semver-set m name (semver-optional name value)) s) [])
    case "build" (transition (semver-mark (semver-set m name (semver-optional name value)) s) [])
    case _ (transition (semver-mark (semver-set m name (semver-core name value)) s) [])

; A container where a part's value is due: the list of a prerelease's or
; a build's identifiers, and nothing else.
def semver-open [s name container]
  match [name container]
    case ["prerelease" :array] (transition (push [:ids name []] s) [])
    case ["build" :array] (transition (push [:ids name []] s) [])
    case [_ :array] (semver-fail (string-join "" [name " is a list"]))
    case _ (semver-fail (string-join "" [name " is an object"]))

; A list of identifiers closes into its part; an empty one is not
; written.
def semver-ids-end [s name texts]
  let [rest (pop s)]
    match (count texts)
      case 0 (transition (semver-mark (semver-set (top rest) name :none) rest) [])
      case _ (transition (semver-mark (semver-set (top rest) name texts) rest) [])

; A prerelease or a build after its sign, or nothing.
def semver-tail [sign part]
  match part
    case :none ""
    case _ (string-join "" [sign (string-join "." part)])

; The version's text, once its root ends.
def semver-text [m]
  match m
    case [:version _ :none _ _ _ _] (semver-fail "it has no major")
    case [:version _ _ :none _ _ _] (semver-fail "it has no minor")
    case [:version _ _ _ :none _ _] (semver-fail "it has no patch")
    case [:version _ ma mi pa pr bu]
      string-join ""
        [(string-join "." [ma mi pa]) (semver-tail "-" pr) (semver-tail "+" bu)]

; A member that is not written has had its value: the version waits for
; its next key.
def semver-skip-done [s]
  transition (pop s) []

; A value completed inside a member that is not written.
def semver-skip-value [s open]
  match (semver-top open)
    case :none (semver-skip-done s)
    case :member (transition (semver-mark [:skip (semver-mark :object open)] s) [])
    case :array (transition s [])
    case :object (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

; A container opens inside a member that is not written.
def semver-skip-open [s open container]
  match (semver-top open)
    case :none (transition (semver-mark [:skip (push container open)] s) [])
    case :member (transition (semver-mark [:skip (push container (semver-mark :object open))] s) [])
    case :array (transition (semver-mark [:skip (push container open)] s) [])
    case :object (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")

; A container closes inside a member that is not written; the last one
; ends the member's value.
def semver-skip-close [s open container]
  match [(semver-top open) container]
    case [:object :object] (semver-skip-closed s (pop open))
    case [:array :array] (semver-skip-closed s (pop open))
    case _ (fail :protocol-order "the events end a container that is not open, or one whose member has no value, which a tree's never do")

def semver-skip-closed [s open]
  match (count open)
    case 0 (semver-skip-done s)
    case _ (transition (semver-mark [:skip open] s) [])

; Inside a member that is not written.
def semver-skip [s open event]
  match event
    case object-start (semver-skip-open s open :object)
    case array-start (semver-skip-open s open :array)
    case (key name)
      match (semver-top open)
        case :object (transition (semver-mark [:skip (semver-mark :member open)] s) [])
        case _ (fail :protocol-order "the events hold a key where a value is due, which a tree's never do")
    case (scalar value) (semver-skip-value s open)
    case object-end (semver-skip-close s open :object)
    case array-end (semver-skip-close s open :array)

; The root: a version is an object.
def semver-root [event]
  match event
    case object-start (transition [[:version :key :none :none :none :none :none]] [])
    case array-start (semver-fail "its root is a list")
    case (scalar value) (semver-fail (string-join "" ["its root is " (semver-kind value)]))
    case _ (fail :protocol-order "the events begin with an end or a key, which a tree's never do")

def semver-step [s event]
  match (semver-top s)
    case :none (semver-root event)
    case [:done] (fail :protocol-order "the events hold more after the root value, which a tree's never do")
    case [:skip open] (semver-skip s open event)
    case [:ids name texts]
      match event
        case (scalar value) (transition (semver-mark [:ids name (push (semver-identifier name (string-join "" ["an identifier of the " name]) value) texts)] s) [])
        case array-end (semver-ids-end s name texts)
        case object-start (semver-fail (string-join "" ["an identifier of the " name " is an object"]))
        case array-start (semver-fail (string-join "" ["an identifier of the " name " is a list"]))
        case _ (fail :protocol-order "the events hold a key or an object's end inside a list, which a tree's never do")
    case [:version :key ma mi pa pr bu]
      match event
        case (key name) (semver-key s [:version :key ma mi pa pr bu] name)
        case object-end (transition [[:done]] [(semver-text [:version :key ma mi pa pr bu])])
        case _ (fail :protocol-order "the events hold a value where a key is due, which a tree's never do")
    case [:version [:value name] ma mi pa pr bu]
      match event
        case (scalar value) (semver-part s [:version [:value name] ma mi pa pr bu] name value)
        case object-start (semver-open s name :object)
        case array-start (semver-open s name :array)
        case _ (fail :protocol-order "the events hold a key or an end where a value is due, which a tree's never do")

def semver-finish [s]
  match (semver-top s)
    case [:done] []
    case :none (fail :protocol-order "the events hold no value, where a tree's hold one")
    case _ (fail :protocol-order "the events ended inside a container, which a tree's never do")

; The render: a version's events in, its text out.
def semver-render [input]
  join ""
    scan-emit [] semver-step semver-finish (events input)
` })
})

function translate (): TranslationParts | undefined {
  return TRANSLATION
}

export {
  translate,
}

export type {
  TranslationPart,
  TranslationParts,
}
